package com.niit.UserToDoTaskService.Service;
import com.niit.UserToDoTaskService.Domain.ToDoList;
import com.niit.UserToDoTaskService.Domain.User;
import com.niit.UserToDoTaskService.Exception.TaskAlreadyPresentException;
import com.niit.UserToDoTaskService.Exception.TaskNotFoundException;
import com.niit.UserToDoTaskService.Exception.UserAlreadyPresentException;
import com.niit.UserToDoTaskService.Exception.UserNotFoundException;

import java.util.*;

public interface UserToDoService
{

    User registerNewUser(User user) throws UserAlreadyPresentException;

    User saveNewTask(ToDoList toDoList, String emailId) throws UserNotFoundException;

    List<ToDoList> getAllTasks(String emailId) throws UserNotFoundException;

    User updateTask(ToDoList toDoList, String emailId) throws UserNotFoundException, TaskNotFoundException;

    // This needs to be edited when we are going to use the autogenerated ids.
    User deleteTask(String emailId, UUID taskId) throws UserNotFoundException, TaskNotFoundException;

    String getUserName(String emailId) throws UserNotFoundException;

    ToDoList getSingleTask(String emailId, UUID id) throws UserNotFoundException,TaskNotFoundException;

    String giveBackTheEmail(String emailId) throws UserNotFoundException;

    // ------------------------------------------- ADMIN USE -----------------------------------------------
    boolean deleteUser(String email) throws UserNotFoundException;

    // ------------------------------------------ Secret Tasks ---------------------------------------------

    List<ToDoList> getAllSecretTasks(String emailId) throws UserNotFoundException;

    User postNewSecretTask(String emailId, UUID taskId) throws UserNotFoundException, TaskNotFoundException;

    User deleteTaskFromSecretTask(String emailId, UUID taskId) throws UserNotFoundException, TaskNotFoundException;

    //------------------------------------------ Secret Task to Normal List Transfer ------------------------------

    User TransferTaskFromSecretTaskToMainList(String emailId, UUID taskId) throws UserNotFoundException, TaskNotFoundException;

    ToDoList GetSingleTaskFromSecretTask(String emailId, UUID id) throws UserNotFoundException, TaskNotFoundException;

    // ---------------------------------------- Secret Password Security -------------------------------------------

    String giveBackTheSecretPassword(String emailId) throws UserNotFoundException;

}
